spring:
  application:
    name: team_celeste
  datasource:
    url: jdbc:mysql://localhost:3306/maquina?useSSL=false&serverTimezone=UTC
    username: root
    password: G!tc3so22
  jpa:
    hibernate:
      ddl-auto: update
