spring:
  application:
    name: team_celeste
  datasource:
    url: jdbc:mysql://localhost:3306/maquina?useSSL=false&serverTimezone=UTC
    username: app_user
    password: rally_preparativo1234
  jpa:
    hibernate:
      ddl-auto: update
